"use client";
import { useState } from "react";
import { type Job } from "@/lib/contracts";
import { message } from "@/lib/client";
import { Modal, Notice } from "./ui";

type DockerHealth = { ready: boolean; detail: string; images: Record<string, { image: string; ready: boolean }> } | undefined;
export function ActionModal({ kind, job, docker, close, submit }: { kind: "verify" | "apply"; job: Job; docker?: DockerHealth; close: () => void; submit: (body: unknown) => Promise<unknown> }) {
  const [runtime, setRuntime] = useState("docker"); const [network, setNetwork] = useState(false);
  const [command, setCommand] = useState(""); const [accepted, setAccepted] = useState(false);
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  return <Modal title={kind === "verify" ? "Run project checks" : "Apply reviewed changes"} onClose={() => { if (!busy) close(); }}>
    <form onSubmit={async event => { event.preventDefault(); setBusy(true); setError(""); try { await submit(kind === "verify" ? { trust_confirmed: true, runtime_mode: runtime, allow_network: runtime === "docker" && network, start_command: runtime === "host" ? command.trim() || undefined : undefined } : { confirm: true }); close(); } catch (error) { setError(message(error)); } finally { setBusy(false); } }}>
      {kind === "verify" ? <><p className="muted">Commands run against the current review copy. Your original project is not mounted in container mode.</p><label className="field">Execution environment<select disabled={busy} value={runtime} onChange={e => { setRuntime(e.target.value); setAccepted(false); }}><option value="docker">Docker · recommended</option><option value="host">Trusted host · no sandbox</option></select></label>{runtime === "docker" ? <><div className={`docker-readiness ${docker?.ready ? "ready" : "attention"}`} role="status"><strong>{docker?.ready ? "Docker is ready" : "Docker needs setup"}</strong><p>{docker?.detail || "Checking the local engine and required images…"}</p>{docker && <div>{Object.values(docker.images).map(item => <code key={item.image}>{item.ready ? "✓" : "×"} {item.image}</code>)}</div>}</div><p className="micro">Browser journeys do not run in this container mode.</p><label className="check-label"><input type="checkbox" checked={network} disabled={busy} onChange={e => { setNetwork(e.target.checked); setAccepted(false); }} /><span>Allow network access for installs and project commands, including local-network access.</span></label></> : <Notice>Host commands can access your computer. A working copy is not a sandbox.</Notice>}<div className="command-preview">{job.commands?.length ? job.commands.map((item, i) => <code key={i}>{Array.isArray(item) ? item.join(" ") : item.argv?.join(" ") || item.label}</code>) : <p>No test/build commands discovered.</p>}</div>{runtime === "host" && <label className="field">Browser start command (optional)<input disabled={busy} value={command} onChange={e => { setCommand(e.target.value); setAccepted(false); }} placeholder={Array.isArray(job.start_command) ? job.start_command.join(" ") : "npm run dev"} /></label>}</> : <p className="muted">This copies the reviewed patch into your original local project. PRAXIS checks for source changes and keeps a backup before applying. Read the diff first.</p>}
      <label className="check-label consent"><input type="checkbox" required checked={accepted} disabled={busy} onChange={e => setAccepted(e.target.checked)} /><span>{kind === "verify" ? "I trust this project and authorize the displayed commands in the selected environment." : "I reviewed the patch and authorize applying it to my original source."}</span></label>
      {error && <Notice error>{error}</Notice>}<div className="modal-actions"><button type="button" className="button" disabled={busy} onClick={close}>Cancel</button><button className="button primary" disabled={!accepted || busy || (kind === "verify" && runtime === "docker" && docker?.ready === false)}>{busy ? "Submitting…" : kind === "verify" ? "Run authorized checks" : "Apply changes"}</button></div>
    </form>
  </Modal>;
}
