"use client";
import { useState } from "react";
import { CheckCheck, ChevronDown, FileCode2, FlaskConical, GitBranch, LoaderCircle, ShieldCheck, Sparkles, Terminal } from "lucide-react";
import { budgetOf, money, type Finding, type Job } from "./types";
import { FixReview } from "./FixReview";

const activeStatuses = ["queued", "scanning", "analyzing", "fixing", "verifying"];
function FindingCard({ finding, selected, onToggle, onFix, canFix }: { finding: Finding; selected: boolean; onToggle: () => void; onFix: () => void; canFix: boolean }) {
  const [open, setOpen] = useState(false);
  return <article className={`finding-card ${selected ? "selected" : ""}`}>
    <div className="finding-heading"><input type="checkbox" aria-label={`Select fix for ${finding.title}`} checked={selected} disabled={!finding.fixable} onChange={onToggle} /><button className="finding-expand" onClick={() => setOpen(!open)} aria-expanded={open}><div className="finding-title"><p className="finding-classification">Severity: {finding.severity.toLowerCase()} · {finding.category.replaceAll("_", " ")}</p><h3>{finding.title}</h3><p>{finding.description}</p></div><ChevronDown className={open ? "rotated" : ""} size={18} /></button></div>
    <div className="finding-meta"><span><FileCode2 size={13} />{finding.location?.file || "Project-wide"}{finding.location?.line ? `:${finding.location.line}` : ""}</span><span>{typeof finding.confidence === "number" ? `${Math.round(finding.confidence <= 1 ? finding.confidence * 100 : finding.confidence)}% confidence` : `${finding.confidence || "Unspecified"} confidence`}</span>{!finding.fixable && <span>Needs your review</span>}</div>
    {open && <div className="finding-details"><div><h4>Why it matters</h4><p>{finding.why || "Review this finding in the context of your project."}</p></div>{finding.evidence && <div><h4>What we found</h4><pre>{finding.evidence}</pre></div>}<div><h4>How to put it right</h4><p>{finding.fix || "Review the affected code and supporting evidence before making a change."}</p></div>{finding.fixable && <button className="secondary single-fix" onClick={onFix} disabled={!canFix}><Sparkles size={13} />Fix this issue</button>}</div>}
  </article>;
}

export function JobReport({ job, busy, onFix, onVerify, onApply, onCancel, onBudget }: { job: Job; busy: boolean; onFix: (ids: string[]) => Promise<void>; onVerify: () => void; onApply: () => void; onCancel: () => Promise<void>; onBudget: () => Promise<void> }) {
  const [selected, setSelected] = useState<string[]>([]);
  const [filter, setFilter] = useState("all");
  const [tab, setTab] = useState<"findings" | "changes" | "activity">("findings");
  const findings = job.findings || [];
  const running = activeStatuses.includes(job.status);
  const fixable = findings.filter(f => f.fixable);
  const selectedValid = selected.filter(id => fixable.some(f => f.id === id));
  const shown = findings.filter(f => filter === "all" || (filter === "fixable" ? f.fixable : ["critical", "high"].includes(f.severity.toLowerCase())));
  const critical = findings.filter(f => ["critical", "high"].includes(f.severity.toLowerCase())).length;
  return <section className="report" aria-label="Project report">
    <div className="report-heading"><div><div className="card-eyebrow">PROJECT WORKSPACE</div><h2>{job.name || job.source.split(/[\\/]/).filter(Boolean).pop() || "Project"}</h2><p className="source-path" title={job.source}>{job.source}</p></div><p className="report-status" role="status">Status: {job.status.replaceAll("_", " ")}</p></div>
    <div className="report-stats"><div><span>Issues found</span><strong>{findings.length}</strong></div><div><span>High priority</span><strong className={critical ? "text-warning" : ""}>{critical}</strong></div><div><span>Files checked</span><strong>{job.files_scanned ?? "—"}</strong></div><div><span>Model spend / budget</span><strong className="spend">{money(job.cost ?? (typeof job.budget === "object" ? job.budget.spent : 0))}<small> / {money(budgetOf(job))}</small></strong></div></div>
    {job.error && <div className="error-banner" role="alert">{job.error}</div>}
    {job.status === "paused" && <div className="pause-banner"><div><strong>The model budget needs your attention.</strong><p>Extend this job’s budget by $5 to let the agents continue.</p></div><button disabled={busy} className="secondary" onClick={onBudget}>Add $5 & resume</button></div>}
    {running && <div className="working-banner"><LoaderCircle className="spin" size={18} /><div><strong>{job.status === "fixing" ? "Your repair team is working" : job.status === "verifying" ? "Checking the changes" : "Looking beneath the surface"}</strong><p>{job.events?.at(-1)?.message || "Preparing the isolated project workspace…"}</p></div><button className="text-button" disabled={busy} onClick={onCancel}>Cancel</button></div>}
    <div className="report-tabs" role="tablist" aria-label="Report view"><button role="tab" aria-selected={tab === "findings"} className={tab === "findings" ? "active" : ""} onClick={() => setTab("findings")}>Findings ({findings.length})</button><button role="tab" aria-selected={tab === "changes"} className={tab === "changes" ? "active" : ""} onClick={() => setTab("changes")}>Changes {job.fix?.diff && <span className="tiny-dot" />}</button><button role="tab" aria-selected={tab === "activity"} className={tab === "activity" ? "active" : ""} onClick={() => setTab("activity")}>Activity & coverage</button></div>
    {tab === "findings" && <><div className="findings-toolbar"><div className="filter-buttons"><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>All issues</button><button className={filter === "priority" ? "active" : ""} onClick={() => setFilter("priority")}>High priority</button><button className={filter === "fixable" ? "active" : ""} onClick={() => setFilter("fixable")}>Fixable</button></div>{fixable.length > 0 && <button className="text-button" onClick={() => setSelected(selectedValid.length === fixable.length ? [] : fixable.map(f => f.id))}><CheckCheck size={14} />{selectedValid.length === fixable.length ? "Clear selection" : "Select fixable"}</button>}</div>
      <div className="findings-list">{shown.map(f => <FindingCard key={f.id} finding={f} selected={selectedValid.includes(f.id)} canFix={["complete", "error"].includes(job.status) && !busy} onFix={() => void onFix([f.id])} onToggle={() => setSelected(prev => prev.includes(f.id) ? prev.filter(id => id !== f.id) : [...prev, f.id])} />)}{!shown.length && <div className="empty-state"><ShieldCheck size={32} /><h3>{running ? "Findings will appear here" : findings.length ? "No findings match this filter" : "No issues detected in the completed checks"}</h3><p>{running ? "PRAXIS Workbench reports evidence as each check finishes." : "Check the coverage tab to understand what was checked and what could not be verified."}</p></div>}</div>
      {findings.length > 0 && <div className="fix-bar"><div><Sparkles size={19} /><span><strong>{selectedValid.length ? `${selectedValid.length} issue${selectedValid.length === 1 ? "" : "s"} selected` : "Ready for a fresh start?"}</strong><small>Agents make changes in a separate copy for your review.</small></span></div><button className="primary" disabled={!selectedValid.length || !["complete", "error"].includes(job.status) || busy} onClick={() => onFix(selectedValid)}><Sparkles size={16} />Instant fix{selectedValid.length > 0 ? ` (${selectedValid.length})` : ""}</button></div>}
    </>}
    {tab === "changes" && <div className="changes-panel">{job.fix ? <FixReview job={job} busy={busy} onVerify={onVerify} onApply={onApply} /> : <div className="empty-state"><GitBranch size={32} /><h3>Your changes will live here</h3><p>Select fixable findings and start Instant Fix to generate a reviewable patch.</p></div>}</div>}
    {tab === "activity" && <div className="activity-panel"><h3>Check coverage</h3><p className="muted">A scan is only as complete as its checks. Unavailable tools and skipped checks are shown here.</p><div className="coverage-grid">{job.coverage?.length ? job.coverage.map((item, index) => <div className="coverage-item" key={index}><div><strong>{item.name || item.tool || "Check"}</strong><span className="coverage-status">Status: {(item.status || "reported").replaceAll("_", " ")}</span></div><p>{item.detail || item.message || "No additional detail."}</p></div>) : <p className="muted">Coverage details will appear when checks run.</p>}</div>{job.languages?.length ? <p className="language-note">Languages detected: {job.languages.join(", ")}</p> : null}<h3 className="activity-title"><Terminal size={17} />Job activity</h3><ol className="timeline">{job.events?.map((event, index) => <li key={index}><span className="timeline-dot" /><div><p>{event.message}</p>{event.time && <time>{event.time}</time>}</div></li>) || <li>Waiting for activity.</li>}</ol>{!running && <button className="secondary" disabled={busy || job.status !== "complete"} onClick={onVerify}><FlaskConical size={15} />Run project verification</button>}</div>}
  </section>;
}
